# Generated by Django 5.2.6 on 2025-09-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_alter_prestamo_libro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='estado',
        ),
    ]
